### ISSUE TITLE
Running `download.sh` doesn't work

### ISSUE THREAD

**Issue by im-stuart** [FusionAuth/fusionauth-theme-helper#1]
Hello.

When pulling the repository anew, I receive the following error upon running `./download.sh`.

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/steventhelin/Development/fusionauth-theme-helper/splitfiles.js:16:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
undefined:1
```

**Steps to reproduce**:
1. Clone the repo
2. Run `npm install`
3. Populate `.env`
4. Run `./download.sh`.

OS: MacOS 12.6 (M1 cpu)
Tried node versions: *16* and *18*

My only suspicion could be filling the `.env` in a wrong way. However I am having a difficult time finding out what exactly the `FUSIONAUTH_URL` should be set tho, thus I've tried filling it out with several URL's I could find/think of, from the Fusion Auth admin platform. When logging the output from `splitfiles.js:14` it outputs `<Buffer >` and no data.

**UPDATE**
Tried pulling it all again, and this time it worked.

**Comment by mooreds** [comment]
@Steven-Thelin what ended up being the issue? Just want to make sure that the docs/script are as helpful as possible.

**Comment by mooreds** [comment]
hmmm. I'll take a todo to provide an example for the fusionauth url.

**Comment by ronie-bairesdev** [comment]
@mooreds, I'm facing the same issue.

When I execute the download.sh file, an error occurs on line 15 of splitfiles.js. It's happening because it tries to do a JSON parsing of contents from the localizedMessages.json file (which in my case is empty).

The question is: why are all files generated in the temp folder empty, after executing the download.sh file?

**Comment by ronie-bairesdev** [comment]
@mooreds, I found the reason: it's because the script executes a cUrl to the following endpoint: https://apadaccess.fusionauth.io/api/theme/[theme_id], and a 401 is been returned. 

That's actually weird since it's placed in the authorization header an API KEY that should have full access to all the endpoints:

![img-1](https://user-images.githubusercontent.com/118214869/211437855-ad2d0801-450f-4599-8089-80643b9a1bb1.png)

**Comment by mooreds** [comment]
@ronie-bairesdev does the theme id exist? Are you using the `key` value, not the `id` value for the api key?

**Comment by ronie-bairesdev** [comment]
@mooreds, I was using the id, not the key. After this change, I was able to successfully execute the download.sh file. 

Thanks for your assistance!

**Comment by mooreds** [comment]
Awesome, glad you figured it out.
